### ISSUE TITLE
[FEATURE] Maps Multi Layer framework with enriched visualization

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/dashboards-maps#15]
**Is your feature request related to a problem?**
Yes [add layers to a map in OpenSearch Dashboard 1.2.0](https://discuss.opendistrocommunity.dev/t/how-to-add-layers-to-a-map-in-opensearch-dashboard-1-2-0/8654)

**What solution would you like?**
Ability to add layers to a map in OpenSearch Dashboard

**Comment by elfisher** [comment]
@vamshin I'll get this added to the roadmap. Can we add the label "roadmap" as well? Thanks!
