### ISSUE TITLE
[BUG] Allow custom vector map to load entire index to join with index pattern

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/dashboards-maps#220]
### What is the bug?
Custom Vector loads only partial documents from OpenSearch. 

### How can one reproduce the bug?
Select Region Map -> LayerOptions -> Choose Custom Vector Map -> select any index contains at least 50 documents. 

### What is the expected behavior?
Region map should join index pattern with all documents from imported vector map.

### What is your host/environment?
All

### Do you have any screenshots?
https://forum.opensearch.org/t/opensearch-dashboards-2-3-0-region-maps-not-working/11967/15

### Do you have any additional context?
N/A

**Comment by Quentame** [comment]
Hi @VijayanB !

Should you add `v2.6.0` tag to this issue ?
As you announed that issue is planned to be fixed on that version here : https://forum.opensearch.org/t/opensearch-dashboards-2-3-0-region-maps-not-working/11967/23

Also: why not using milestones instead of tags ? https://github.com/opensearch-project/dashboards-maps/milestones

Thanks.

**Comment by Quentame** [comment]
As you may expect, I am having the same issue.

Here, I am trying to display the 96 French departments into map and I am only seeing 10 so far.

Plus, I have noticed that a colleague of mine also does see 10 but not the same 10 as me, see screenshot:
![OSD_map_departments_not_showing_all_geojson_entries](https://user-images.githubusercontent.com/14821482/217566746-3b53e56b-abf4-4923-98f3-a5a2d89785ef.png)
On the left: a map viz from a colleague via Teams --------------- On the right: the same viz on my browser
EDIT: can't reproduce today

GeoJSON: https://france-geojson.gregoiredavid.fr/repo/departements.geojson from https://france-geojson.gregoiredavid.fr/
OS & OSD version: 2.5.0

Thanks

**Comment by VijayanB** [comment]
> Hi @VijayanB !
> 
> Should you add `v2.6.0` tag to this issue ? As you announed that issue is planned to be fixed on that version here : https://forum.opensearch.org/t/opensearch-dashboards-2-3-0-region-maps-not-working/11967/23
> 
> Also: why not using milestones instead of tags ? https://github.com/opensearch-project/dashboards-maps/milestones
> 
> Thanks.

Thanks for reporting issue. I believe we use tags to keep it consistent with other plugins. However, let me also take a look at advantage of using milestone and how can we incorporate in this plugin.

**Comment by VijayanB** [comment]
Fix is merged in OpenSearchDashboards repository. This will be available in 2.6
