### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch-Dashboards distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/dashboards-maps#26]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

A bit different from the OpenSearch Gradle IntegTest, the cypress test on dashboards need to be added to https://github.com/opensearch-project/opensearch-dashboards-functional-test

**Comment by junqiu-lei** [comment]
Since PR merged, going to close this issue.

**Comment by peterzhuamazon** [comment]
We will keep it open until 2.2.0 is out to make sure it is running well on jenkins.

**Comment by junqiu-lei** [comment]
Talked with @peterzhuamazon, we now can close this issue. The test report can be checked from https://github.com/opensearch-project/opensearch-build/issues/2271#issuecomment-1210054491 https://github.com/opensearch-project/opensearch-build/issues/2271#issuecomment-1210251678
