### ISSUE TITLE
Add plugin to part of opensearch build

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/dashboards-maps#3]
Follow this guide to include this as part of 2.2-snapshot
https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#opensearch-build

- [x] Add it to opensearch-build/meta
- [x] Add it to opensearch-plugins
- [x] Add it to 2.2 manifest

Also, tracked here: https://github.com/opensearch-project/opensearch-build/issues/2346

**Comment by junqiu-lei** [comment]
dashboard-maps merged it to manifest. https://github.com/opensearch-project/opensearch-build/pull/2411, going to close it.
