### ISSUE TITLE
(OUI Next Theme) Maps

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/dashboards-maps#448]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

<img width="1281" alt="Screen Shot 2023-07-25 at 4 06 12 PM" src="https://github.com/opensearch-project/oui/assets/105819041/e54c5fd6-3c7a-4f2d-a310-3b07daf4983e">

- [x] Draw rectangle button icon is set to `primary`, but should be set to `ghost` which will adjust appropriately between dark & light modes 
- [x] Draw polygon icon is set to `inherit` color, therefore is showing too dark in dark mode, should be set to `ghost` which will adjust appropriately between dark & light modes 
- [x] While in dark mode, Zoom controls showing in light mode 
- [x] While in dark mode, map tiles showing in light mode

**Comment by junqiu-lei** [comment]
There are some open source styles from https://openmaptiles.org/styles, and we can also generate our own map style by https://openmaptiles.org/docs/style/maputnik/. @KrooshalUX we might need your help to choose the dark style we are going to use for base tile maps. Thanks!

**Comment by KrooshalUX** [comment]
Thanks @junqiu-lei  - I have taken a look at the styles, and based on our previous conversation we are limited to the GL styles. 

The dark tiles provided in the GL styles "Dark Matter" https://openmaptiles.org/styles/#dark-matter is too low contrast however. 

Is it possible to translate the style from "Dark" https://openmaptiles.org/styles/#dark - which is not available in GL-  into a custom map style using Maputnik as mentioned above? This one is much more legible and provides better contrast between water, land and boundaries.

**Comment by junqiu-lei** [comment]
Hi @KrooshalUX, we need to use the GL styles for our vector tile service, we can make some adjust based on the "Dark Matter" style on the open source tool https://maputnik.github.io/editor and get the output style json file.

In the maputnik page, you can click the "Open" and select "Dark Matter" or other style as base style and then edit.

This is the one example I just made a little change on the water color from "Dark Matter".

<img width="2551" alt="image" src="https://github.com/opensearch-project/dashboards-maps/assets/90288540/5e667cb0-2dd3-4656-a628-e861ce95e74d">

**Comment by KrooshalUX** [comment]
@junqiu-lei This is a great start, can we continue to match the styles in the editor to 'Dark' or as close to it, and follow up with screenshots?

**Comment by junqiu-lei** [comment]
The PR merged, we can create a issue to track the higher contrast dark style.
