### ISSUE TITLE
[FEATURE] Support Multiple Data Source in Maps Dashboards Plugin

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/dashboards-maps#584]
### Is your feature request related to a problem?
With multiple data source enabled, users of OpenSearch Dashboards are able to create data source connections and query local and remote OpenSearch clusters. Enabling multiple data source at dashboards plugin would ensure users that have been using the multiple data source feature to have a consistent experience in the dashboard, and allows users to use the same dashboard for different clusters.

### What solution would you like?
Support multiple data source in the maps dashboards plugin 

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by BionIT** [comment]
Thanks @kgcreative @junqiu-lei for the sync up! A quick summary from the offline meeting: Maps plugin uses index pattern which already supports multiple data source. During the walk through, we did find a few things we need to address before close out:
1. Change the label from `Data source` to `Index pattern` at the location below - @junqiu-lei 
![Screenshot 2024-02-19 at 3 37 51 PM](https://github.com/opensearch-project/dashboards-maps/assets/17714150/61b69258-3328-4985-8ab0-901d88d0aadb)
2. Fix the combo box which shows 2 options selected  - @junqiu-lei @BionIT 
3. Add data source connection name as prefix to the selector - @BionIT will look into this and evaluate if we can use the component in discover page

**Comment by junqiu-lei** [comment]
Thanks @BionIT for the clear summary!

**Comment by BionIT** [comment]
Thanks @junqiu-lei for merging the label change! Now we have 1-3 closed. 
@kgcreative should we do a quick demo for the maps plugin before closing this out?

**Comment by kgcreative** [comment]
@junqiu-lei can you either post before/after screenshots, or a screen recording here? I think we can review and close out async

**Comment by junqiu-lei** [comment]
@kgcreative @BionIT Hi, I made a screen recording for the maps multi data source support, please review, thanks!

https://github.com/opensearch-project/dashboards-maps/assets/90288540/9eb34012-9a4b-4350-b83b-1ab5dfc72b21

**Comment by kgcreative** [comment]
LGTM! Ship it!
