### ISSUE TITLE
Cypress CI failed with "detected that the Electron Renderer process just crashed"

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/dashboards-maps#592]
### What is the bug?
The local run can be passed but failed on CI environment
```
  Documents layer

We detected that the Electron Renderer process just crashed.

We have failed the current spec but will continue running the next spec.

This can happen for a number of different reasons.

If you're running lots of tests on a memory intense application.
  - Try increasing the CPU/memory on the machine you're running on.
  - Try enabling experimentalMemoryManagement in your config file.
  - Try lowering numTestsKeptInMemory in your config file during 'cypress open'.

You can learn more here:

https://on.cypress.io/renderer-process-crashed

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 18 seconds                                                             │
  │ Spec Ran:     documentsLayer.cy.js                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

### How can one reproduce the bug?
Failed on CI, example: https://github.com/opensearch-project/dashboards-maps/actions/runs/8053561689/job/21996241052

### What is the expected behavior?
Pass CI test

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)

@junqiu-lei Was this fixed?

**Comment by junqiu-lei** [comment]
Hi @dblock this CI issue most likely related to cypress version/github runner capacities, we are trying to replace this maps repo CI with test pipeline from [opensearch-dashboards-functional-test](https://github.com/opensearch-project/opensearch-dashboards-functional-test) which is stable without issue. The [maps tests](https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/5952/pipeline) for 2.15 version on release pipeline CI currently is passed. Adding tag with 2.16 for this issue.
