### ISSUE TITLE
[FEATURE] Visualization for GeoHex Grid

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/dashboards-maps#64]
### Is your feature request related to a problem?
No

### What solution would you like?
Ability to show Hex rings on the map in visualization similar to Geo tiles grid

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by VijayanB** [comment]
This is duplicate of #59 . Shall we close this?

**Comment by vamshin** [comment]
Good catch! Closing. Thanks
