### ISSUE TITLE
[BUG] Split multiple plugins into their own repositories

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-maps#95]
### What is the bug?

Coming from https://github.com/opensearch-project/opensearch-build/pull/2934#issuecomment-1329614301 and  https://github.com/opensearch-project/opensearch-build/issues/2188, it looks like we have a monorepo being developed here in a feature branch.

https://github.com/opensearch-project/dashboards-maps/tree/main/custom_import_map
https://github.com/opensearch-project/dashboards-maps/tree/feature/new-maps/maps_dashboards

### What is the expected behavior?

Split monorepo into full, standalone plugin repos.

**Comment by navneet1v** [comment]
@dblock what is the issue with having more than 1 plugin in a repo?

**Comment by navneet1v** [comment]
Tagging @CEHENKLE.

**Comment by dblock** [comment]
> @dblock what is the issue with having more than 1 plugin in a repo?
> 
> Both the plugins are OSD plugins.

Take a look at https://github.com/opensearch-project/opensearch-build/issues/2188 and the long discussion in it.

**Comment by heemin32** [comment]
> > @dblock what is the issue with having more than 1 plugin in a repo?
> > Both the plugins are OSD plugins.
> 
> Apologies for the late reply, didn't see the tag. Take a look at [opensearch-project/opensearch-build#2188](https://github.com/opensearch-project/opensearch-build/issues/2188) and the long discussion in it.

Hi @dblock, in the thread, you mentioned that `The intention of this issue was to split front-end and back-end plugins, for those other things I'd defer to the team that understands the code dependencies better. Maybe open another issue on those? How often do they release and what are their dependencies?`. In our case, both are front-end. We are not having front-end and back-end plugin in a single repo.

**Comment by navneet1v** [comment]
> We are not having front-end and back-end plugin in a single repo.

Hi @heemin32 
I have clarified with @dblock on this. The time when the proposal was created it was for splitting the repos having frontend and backend plugins. But on based on recent updates, the proposal is valid for this repo too.

**Comment by VijayanB** [comment]
Now both plugins are merged into single plugin. Thanks @dblock for feedback.
