### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/dashboards-maps#99]
As per https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#plugin-naming-conventions,

[Plugin ID needs to be lowercase camelcase](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-dashboard-plugins-1)

[Meta needs to be updated to match the plugin name](https://github.com/opensearch-project/opensearch-plugins/blob/main/dashboards-plugins/.meta)

Also, as per https://github.com/opensearch-project/opensearch-build/issues/2188, we should get rid of the folder and move [opensearch_dashboards.json](https://github.com/opensearch-project/dashboards-maps/blob/main/custom_import_map/opensearch_dashboards.json) to the root folder of the repo.

Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by junqiu-lei** [comment]
Hi @mnkugler, I think we resolved all the issues you mentioned, could you help check? Thanks!

> Plugin ID needs to be lowercase camelcase

we uses `customImportMapDashboards` at [opensearch_dashboards.json](https://github.com/opensearch-project/dashboards-maps/blob/main/opensearch_dashboards.json#L2)

> Meta needs to be updated to match the plugin name

https://github.com/opensearch-project/opensearch-plugins/pull/195 merged to resolved it

> we should get rid of the folder and move opensearch_dashboards.json to the root folder of the repo.

Yes, it's under repo root path

**Comment by mnkugler** [comment]
Hi @junqiu-lei -- everything looks good. Thanks for resolving all the issues!
